### ISSUE TITLE
npm run dev throws error: exit code 2

### ISSUE THREAD

**Issue by mansoorbarri** [zeon-studio/hugoplate#152]
### What is your Hugo Extended Version

hugo v0.111.3+extended

### What is your Go Version

go version go1.19.8

### What is your Node.js Version

Node.js v18.19.0

### What is your Operating System

Debian Linux

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

the website should run at localhost:1313

### Steps to Reproduce

just follow the guide.

### Additional Information

full error: 
```
❯ pnpm dev 

> hugoplate@1.17.0 dev /home/anar/Downloads/hugoplate
> hugo server

WARN 2024/10/17 10:34:18 Module "hugoplate.netlify.app" is not compatible with this Hugo version; run "hugo mod graph" for more information.
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/gohugoio/hugo/resources/page.PermalinkExpander.validate({0xc000768540?, 0x0?, 0xc000a95f20?}, {0x0?, 0x0?})
	github.com/gohugoio/hugo/resources/page/permalinks.go:183 +0x23b
github.com/gohugoio/hugo/resources/page.PermalinkExpander.parse({0xc000768540?, 0x0?, 0xc000a95f20?}, 0x8?)
	github.com/gohugoio/hugo/resources/page/permalinks.go:126 +0x136
github.com/gohugoio/hugo/resources/page.NewPermalinkExpander(0xc000a95f20)
	github.com/gohugoio/hugo/resources/page/permalinks.go:95 +0x7a5
github.com/gohugoio/hugo/resources.NewSpec(0xc000a95f20, 0xc000a95f50, {0x26982a0, 0xc00036a2e0}, {0x26b69f0, 0xc000a942d0}, {0x26982c0?, 0xc0000146b0}, 0xc00083a8c0, {0xc0001f1900, ...}, ...)
	github.com/gohugoio/hugo/resources/resource_spec.go:76 +0x205
github.com/gohugoio/hugo/deps.New({{0x26b69f0, 0xc000a942d0}, 0xc000872540, 0xc00084c900, {0x0, 0x0}, {0x26b3f40, 0xc000706f50}, {0xc000ab4000, 0x22, ...}, ...})
	github.com/gohugoio/hugo/deps/deps.go:291 +0x705
github.com/gohugoio/hugo/hugolib.configLoader.applyDeps({{0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)
	github.com/gohugoio/hugo/hugolib/hugo_sites.go:518 +0x31e
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x26b69f0, 0xc000a942d0}, 0xc000872540, 0x0, {0x0, 0x0}, {0x26b3f40, 0xc000706f50}, {0x0, 0x0, ...}, ...}, ...)
	github.com/gohugoio/hugo/hugolib/hugo_sites.go:405 +0x766
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x26b69f0, 0xc000a942d0}, 0xc000872540, 0x0, {0x0, 0x0}, {0x26b3f40, 0xc000706f50}, {0x0, 0x0, ...}, ...})
	github.com/gohugoio/hugo/hugolib/hugo_sites.go:554 +0x158
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	github.com/gohugoio/hugo/commands/commandeer.go:501 +0x8d8
sync.(*Once).doSlow(0xc000706f50?, 0x1fb730b?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0009a8a00)
	github.com/gohugoio/hugo/commands/commandeer.go:426 +0xaaa
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x1, 0xc00039e0f0, {0x2698240?, 0xc0004abbc0}, 0xc00038a520, {0x0, 0x0, 0x0})
	github.com/gohugoio/hugo/commands/commandeer.go:227 +0x31f
github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0x0?, 0x0?, 0x1f9c039?, {0x2698240?, 0xc0004abbc0?}, 0x0?)
	github.com/gohugoio/hugo/commands/hugo.go:125 +0x3b
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc0004abbc0, 0xc000178600, {0x0?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/server.go:257 +0x1cd
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc000178600?, {0x3743198?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/server.go:96 +0x36
github.com/spf13/cobra.(*Command).execute(0xc000178600, {0x3743198, 0x0, 0x0})
	github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00098fb00)
	github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/gohugoio/hugo/commands.Execute({0xc000040050, 0x1, 0x1})
	github.com/gohugoio/hugo/commands/hugo.go:92 +0xbd
main.main()
	github.com/gohugoio/hugo/main.go:23 +0x56
 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by tfsomrat** [comment]
Hey @mansoorbarri, please update your hugo version to resolve the issue.
