### ISSUE TITLE
Removing dark mode causes an error

### ISSUE THREAD

**Issue by nativerez** [zeon-studio/hugoplate#61]
Running `npm run remove-darkmode` throws an error

> hugoplate@1.9.5 remove-darkmode
> node ./scripts/removeDarkmode.js && yarn format

node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'layouts'
    at Object.readdirSync (node:fs:1450:3)
    at removeDarkModeFromPages (/Users/jamie.wallace/Sites/hugoplate/scripts/removeDarkmode.js:30:20)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/jamie.wallace/Sites/hugoplate/scripts/removeDarkmode.js:16:10)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'layouts'
}

**Comment by tfsomrat** [comment]
Hey @nativerez, I have checked it again. and it's working just fine. Please download the theme, and open the terminal on the root folder of this theme. run `yarn remove-darkmode`. and it should work. you can capture the full process and upload it here if it doesn't work. I am here to help. thanks

**Comment by huima** [comment]
Issue here is that the script does not work if you setup your project with the script first. It works if you download the projects and run the script, and then set up the project.

**Comment by huima** [comment]
I just tested this and noticed that the remove dark mode script does not work if you run it after you have created the project by running the "npm run project-setup" step.

Problem is understandable as these steps come in order in the readme.

Would be good if the script would check if the theme has already been installed by running the project-setup, and then use suitable paths there.

**Comment by tfsomrat** [comment]
hey @huima, I have updated the readme file about this topic.
