### ISSUE TITLE
ERROR POSTCSS: failed to transform "css/style-lazy.css"

### ISSUE THREAD

**Issue by msdundar** [zeon-studio/hugoplate#87]
### What is your Hugo Extended Version

0.122.0

### What is your Go Version

1.21.3

### What is your Node.js Version

20.11.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When I tried to build my site, I suddenly started to get these errors and can't understand why.

### Steps to Reproduce

In my local environment, both `npm run build` and `npm run preview` work fine. However, on Cloudflare, I keep getting this error.

### Code Reproduction URL

https://github.com/msdundar/holidays.rest

### Additional Information

Deployment log:

```
2024-02-04T14:44:45.306037Z	Cloning repository...
2024-02-04T14:44:46.452711Z	From https://github.com/msdundar/holidays.rest
2024-02-04T14:44:46.45335Z	 * branch            3636220dc5d09f6b10bb034ddf24f2c4a67baa05 -> FETCH_HEAD
2024-02-04T14:44:46.453543Z	
2024-02-04T14:44:46.503309Z	HEAD is now at 3636220 again
2024-02-04T14:44:46.503826Z	
2024-02-04T14:44:46.597Z	
2024-02-04T14:44:46.597666Z	Using v2 root directory strategy
2024-02-04T14:44:46.626542Z	Success: Finished cloning repository files
2024-02-04T14:44:51.057773Z	Detected the following tools from environment: nodejs@20.11.0, golang@1.21.3, hugo@extended_0.122.0, npm@9.6.7
2024-02-04T14:44:51.058435Z	Installing nodejs 20.11.0
2024-02-04T14:44:51.570145Z	Trying to update node-build... ok
2024-02-04T14:44:51.798027Z	Downloading node-v20.11.0-linux-x64.tar.gz...
2024-02-04T14:44:51.798316Z	-> https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.gz
2024-02-04T14:44:54.110863Z	Installing node-v20.11.0-linux-x64...
2024-02-04T14:44:54.666301Z	Installed node-v20.11.0-linux-x64 to /opt/buildhome/.asdf/installs/nodejs/20.11.0
2024-02-04T14:44:54.666768Z	
2024-02-04T14:44:55.84903Z	Installing golang 1.21.3
2024-02-04T14:44:55.975967Z	[32mPlatform 'linux' supported![39m
2024-02-04T14:44:56.093703Z	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-02-04T14:44:56.094146Z	                                 Dload  Upload   Total   Spent    Left  Speed
2024-02-04T14:44:56.412819Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 63.5M  100 63.5M    0     0   198M      0 --:--:-- --:--:-- --:--:--  199M
2024-02-04T14:44:56.429731Z	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-02-04T14:44:56.430063Z	                                 Dload  Upload   Total   Spent    Left  Speed
2024-02-04T14:44:56.535773Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    64  100    64    0     0    602      0 --:--:-- --:--:-- --:--:--   603
2024-02-04T14:44:56.53931Z	verifying checksum
2024-02-04T14:44:56.862781Z	/opt/buildhome/.asdf/downloads/golang/1.21.3/archive.tar.gz: OK
2024-02-04T14:44:56.863315Z	[32mchecksum verified[39m
2024-02-04T14:44:58.964616Z	Installing hugo extended_0.122.0
2024-02-04T14:44:59.100676Z	* Downloading hugo release extended_0.122.0...
2024-02-04T14:45:00.723135Z	hugo extended_0.122.0 installation was successful!
2024-02-04T14:45:01.036172Z	Installing project dependencies: npm install --progress=false
2024-02-04T14:45:11.288482Z	
2024-02-04T14:45:11.288706Z	added 170 packages, and audited 171 packages in 10s
2024-02-04T14:45:11.28898Z	
2024-02-04T14:45:11.289169Z	42 packages are looking for funding
2024-02-04T14:45:11.289281Z	  run `npm fund` for details
2024-02-04T14:45:11.289983Z	
2024-02-04T14:45:11.290188Z	found 0 vulnerabilities
2024-02-04T14:45:11.309228Z	Executing user command: npm run build
2024-02-04T14:45:11.931126Z	
2024-02-04T14:45:11.931416Z	> hugoplate@1.11.1 build
2024-02-04T14:45:11.931611Z	> hugo --gc --minify --templateMetricsHints --forceSyncStatic -e production
2024-02-04T14:45:11.931773Z	
2024-02-04T14:45:14.256788Z	hugo: downloading modules …
2024-02-04T14:45:15.225269Z	hugo: collected modules in 2969 ms
2024-02-04T14:45:15.228559Z	Start building sites … 
2024-02-04T14:45:15.228773Z	hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended linux/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio
2024-02-04T14:45:15.228937Z	
2024-02-04T14:45:22.668655Z	ERROR POSTCSS: failed to transform "css/style-lazy.css" (text/css): 
2024-02-04T14:45:22.669124Z	warn - The safelist pattern `/^swiper-/` doesn't match any Tailwind CSS classes.
2024-02-04T14:45:22.66946Z	warn - Fix this pattern or remove it from your `safelist` configuration.
2024-02-04T14:45:22.669702Z	warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
2024-02-04T14:45:22.669883Z	SyntaxError: Unexpected end of JSON input
2024-02-04T14:45:22.669999Z	    at JSON.parse (<anonymous>)
2024-02-04T14:45:22.670121Z	    at defaultExtractor (/opt/buildhome/repo/www/postcss.config.js:4:27)
2024-02-04T14:45:22.670223Z	    at b (/opt/buildhome/repo/www/node_modules/purgecss/lib/purgecss.js:1:4289)
2024-02-04T14:45:22.670325Z	    at PurgeCSS.extractSelectorsFromFiles (/opt/buildhome/repo/www/node_modules/purgecss/lib/purgecss.js:1:6443)
2024-02-04T14:45:22.670423Z	    at async /opt/buildhome/repo/www/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1153
2024-02-04T14:45:22.670518Z	    at async LazyResult.runAsync (/opt/buildhome/repo/www/node_modules/postcss/lib/lazy-result.js:298:15)
2024-02-04T14:45:22.670637Z	    at async Promise.all (index 0)
2024-02-04T14:45:22.670741Z	Total in 10420 ms
2024-02-04T14:45:22.670842Z	Error: error building site: POSTCSS: failed to transform "css/style.css" (text/css): 
2024-02-04T14:45:22.670941Z	warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
2024-02-04T14:45:22.671041Z	warn - https://tailwindcss.com/docs/content-configuration
2024-02-04T14:45:22.671149Z	SyntaxError: Unexpected end of JSON input
2024-02-04T14:45:22.671243Z	    at JSON.parse (<anonymous>)
2024-02-04T14:45:22.671342Z	    at defaultExtractor (/opt/buildhome/repo/www/postcss.config.js:4:27)
2024-02-04T14:45:22.671442Z	    at b (/opt/buildhome/repo/www/node_modules/purgecss/lib/purgecss.js:1:4289)
2024-02-04T14:45:22.671545Z	    at PurgeCSS.extractSelectorsFromFiles (/opt/buildhome/repo/www/node_modules/purgecss/lib/purgecss.js:1:6443)
2024-02-04T14:45:22.671644Z	    at async /opt/buildhome/repo/www/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1153
2024-02-04T14:45:22.671743Z	    at async LazyResult.runAsync (/opt/buildhome/repo/www/node_modules/postcss/lib/lazy-result.js:298:15)
2024-02-04T14:45:22.671841Z	    at async Promise.all (index 0)
2024-02-04T14:45:22.671941Z	npm notice 
2024-02-04T14:45:22.672041Z	npm notice New minor version of npm available! 10.2.4 -> 10.4.0
2024-02-04T14:45:22.672146Z	npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
2024-02-04T14:45:22.672243Z	npm notice Run `npm install -g npm@10.4.0` to update!
2024-02-04T14:45:22.672341Z	npm notice 
2024-02-04T14:45:22.687371Z	Failed: Error while executing user command. Exited with error code: 1
2024-02-04T14:45:22.701559Z	Failed: build command exited with code: 1
2024-02-04T14:45:23.769338Z	Failed: error occurred while running build command
```

**Comment by msdundar** [comment]
I got the above error in Cloudflare. However, it's the same error when I try to deploy the site on Vercel or Render.

**Comment by msdundar** [comment]
It was a configuration error, it's fixed now.
